runtime: java
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "21"

entrypoint: java -jar mmr-0.0.1-SNAPSHOT.jar
# Instance configuration
instance_class: F4

# Automatic scaling configuration
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 300

# Network configuration
network:
  session_affinity: true


# Environment variables
env_variables:
  SPRING_PROFILES_ACTIVE: "prod"
  JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75 -Xms1G -Xmx2G"
  CORS_ALLOWED_ORIGINS: "https://it-342-memoire.vercel.app,http://localhost:5173"