runtime: java
env: flex
runtime_config:
  operating_system: ubuntu22
  runtime_version: 21

# Configure automatic scaling
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.7

# Configure resources
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20

# Enable WebSocket support
network:
  session_affinity: true  # Enable session affinity for WebSockets

# Environment variables
env_variables:
  SPRING_PROFILES_ACTIVE: prod
  ALLOWED_ORIGINS: "*"

